
name: Auto Comment on New Issue
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to new issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your contribution!
